### ISSUE TITLE
Examples won't run

### ISSUE THREAD

**Issue by RevDrDR** [jgillula/rpi-rfm69#12]
Hello and thanks for this project. I'm trying to get the RFM69-915MHz from Sparkfun running with a RPi 3B+. Your code looks promising and I appreciate the documentation -- it's far more thorough than any I've seen. Unfortunately, I'm still missing some steps somehow. When I try to run the example code it throws errors and then fails to get the radio running. I've installed your library (thanks!) and cloned the repository, but it still seems like some files aren't in the right spots? I'm not sure, but if you could provide steps from after I clone the repo to get the sample tx rx code working, I'd be so grateful. Also, how do you know what spi device to use? You have it assigned as 1, but everywhere else I've seen is assigned as 0.

**Comment by jgillula** [comment]
Sincere apologies for the delay in replying to this!

Can you share what the errors are? For me, the following works if I clone the repo:

```
git clone https://github.com/jgillula/rpi-rfm69.git
cd rpi-rfm69
cp examples/example_rxtx.py . # This copies the example script to a place where when we run it, it should find the library in the RFM69 folder
python3 example_rxtx.py
```

As for the spi device, I use 1 because that's what the Adafruit RFM69HCW Transceiver Radio Bonnet I have uses. I believe it depends on which SPIO pin the radio is connected to, SPIO CE0 (Pi pin 24) or SPIO CE1 (Pi pin 26).

**Comment by jgillula** [comment]
Since there hasn't been any activity on this issue in a month, I'm going to go ahead and close it. If you still need help, please don't hesitate to post a new issue.
