### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by rufusclark** [jgillula/rpi-rfm69#27]
I believe GPIO Pin 25 has been miss labelled as GPIO 5 in your documentations (according to BOARD number 22 and fritzing diagram) within hookup page in the final column of your pinout page.

<img width="341" alt="image" src="https://github.com/jgillula/rpi-rfm69/assets/50201718/6560d663-07f9-483a-833e-b100c975df2c">
<img width="532" alt="image" src="https://github.com/jgillula/rpi-rfm69/assets/50201718/af061adf-1cf1-44f1-aef5-da0ab083dae6">

**Comment by jgillula** [comment]
It's been a while since I've looked at this, but I think what I'm seeing for the reset pin is:

* The default in the code uses Pi pin 29, GPIO 5
* The diagram shows Pi pin 22, GPIO 25
* The table shows the impossible combo of Pi in 22, GPIO 5

I think the right way to fix this is to fix the diagram and table to match the default in the code, namely Pi pin 29, GPIO 5.
